services:
  # =============================================================================
  # VPN CLIENT SERVICE - Your VPN Connection Provider
  # =============================================================================
  vpn-client:
    image: qmcgaw/gluetun
    container_name: vpn-client
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ../../vpn-client:/gluetun
    environment:
      - UPDATER_PERIOD=${UPDATER_PERIOD:-24h}
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      - OPENVPN_USER=${VPN_USER}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - FIREWALL_OUTBOUND_SUBNETS=172.28.0.0/16
    restart: always

  # =============================================================================
  # VPN SENTINEL CLIENT - Monitors from inside VPN network
  # =============================================================================
  vpn-sentinel-client:
    image: curlimages/curl:latest
    container_name: vpn-sentinel-client
    environment:
      - VPN_SENTINEL_SERVER_API_BASE_URL=http://vpn-sentinel-server:5000
      - VPN_SENTINEL_SERVER_API_PATH=/api/v1
      - VPN_SENTINEL_CLIENT_ID=${VPN_SENTINEL_CLIENT_ID:-vpn-monitor-main}
      - VPN_SENTINEL_API_KEY=${VPN_SENTINEL_API_KEY}
      - TZ=${TZ:-UTC}
    volumes:
      - ../../vpn-sentinel-client/vpn-sentinel-client.sh:/tmp/vpn-sentinel-client.sh:ro
    network_mode: service:vpn-client
    restart: always
    depends_on:
      - vpn-client
      - vpn-sentinel-server

  # =============================================================================
  # VPN SENTINEL SERVER - Central monitoring server
  # =============================================================================
  vpn-sentinel-server:
    build: ../../vpn-sentinel-server
    container_name: vpn-sentinel-server
    ports:
      - "5000:5000"
      - "8080:8080"
    environment:
      - VPN_SENTINEL_SERVER_API_PORT=5000
      - VPN_SENTINEL_SERVER_DASHBOARD_PORT=8080
      - VPN_SENTINEL_API_KEY=${VPN_SENTINEL_API_KEY}
      - TZ=${TZ:-UTC}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - VPN_SENTINEL_TLS_CERT_PATH=${VPN_SENTINEL_TLS_CERT_PATH}
      - VPN_SENTINEL_TLS_KEY_PATH=${VPN_SENTINEL_TLS_KEY_PATH}
      - VPN_SENTINEL_SERVER_ALLOWED_IPS=${VPN_SENTINEL_SERVER_ALLOWED_IPS}
      - VPN_SENTINEL_SERVER_RATE_LIMIT_REQUESTS=${VPN_SENTINEL_SERVER_RATE_LIMIT_REQUESTS:-30}
    volumes:
      - ../../vpn-sentinel-server:/app:ro
      - ${VPN_SENTINEL_TLS_CERT_PATH:-../../certs/server.crt}:/certs/server.crt:ro
      - ${VPN_SENTINEL_TLS_KEY_PATH:-../../certs/server.key}:/certs/server.key:ro
    networks:
      - vpn-sentinel-internal
      - vpn-sentinel-server
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/v1/health"]
      interval: 60s
      timeout: 10s
      retries: 3

networks:
  vpn-sentinel-internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
  vpn-sentinel-server:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16
