services:
  vpn-sentinel-client:
    build: ../../vpn-sentinel-client
    container_name: vpn-sentinel-client
    environment:
      - VPN_SENTINEL_URL=${VPN_SENTINEL_URL}
      - VPN_SENTINEL_API_PATH=${VPN_SENTINEL_API_PATH}
      - VPN_SENTINEL_CLIENT_ID=${VPN_SENTINEL_CLIENT_ID}
      - VPN_SENTINEL_API_KEY=${VPN_SENTINEL_API_KEY}
      - TZ=${TZ}
      - VPN_SENTINEL_TLS_CERT_PATH=${VPN_SENTINEL_TLS_CERT_PATH}
      - VPN_SENTINEL_DEBUG=${VPN_SENTINEL_DEBUG}
      - VPN_SENTINEL_GEOLOCATION_SERVICE=${VPN_SENTINEL_GEOLOCATION_SERVICE}
    restart: unless-stopped
