services:
  # =============================================================================
  # VPN CLIENT SERVICE - Your VPN Connection Provider
  # =============================================================================
  vpn-client:
    image: qmcgaw/gluetun
    container_name: vpn-client
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ../../vpn-client:/gluetun
    environment:
      - UPDATER_PERIOD=${UPDATER_PERIOD:-24h}
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      - OPENVPN_USER=${VPN_USER}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - FIREWALL_OUTBOUND_SUBNETS=172.28.0.0/16
    restart: always

  # =============================================================================
  # VPN SENTINEL CLIENT - Monitors from inside VPN network
  # =============================================================================
  vpn-sentinel-client:
    build: ../../vpn-sentinel-client
    container_name: vpn-sentinel-client
    volumes:
      - ./certs:/certs:ro
    environment:
      - VPN_SENTINEL_URL=http://vpn-sentinel-server:5000
      - VPN_SENTINEL_API_PATH=/api/v1
      - VPN_SENTINEL_CLIENT_ID=${VPN_SENTINEL_CLIENT_ID:-vpn-monitor-main}
      - VPN_SENTINEL_API_KEY=${VPN_SENTINEL_API_KEY}
      - TZ=${TZ:-UTC}
      - VPN_SENTINEL_TLS_CERT_PATH=${VPN_SENTINEL_TLS_CERT_PATH}
      - VPN_SENTINEL_DEBUG=${VPN_SENTINEL_DEBUG}
      - VPN_SENTINEL_GEOLOCATION_SERVICE=${VPN_SENTINEL_GEOLOCATION_SERVICE:-auto}
    network_mode: service:vpn-client
    restart: always
    depends_on:
      - vpn-client
      - vpn-sentinel-server

  # =============================================================================
  # VPN SENTINEL SERVER - Central monitoring server
  # =============================================================================
  vpn-sentinel-server:
    build: ../../vpn-sentinel-server
    container_name: vpn-sentinel-server
    volumes:
      - ./certs:/certs:ro
    ports:
      - "5000:5000"
      - "8080:8080"
    environment:
      - VPN_SENTINEL_SERVER_API_PORT=5000
      - VPN_SENTINEL_SERVER_DASHBOARD_PORT=8080
      - VPN_SENTINEL_API_KEY=${VPN_SENTINEL_API_KEY}
      - TZ=${TZ:-UTC}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - VPN_SENTINEL_TLS_CERT_PATH=${VPN_SENTINEL_TLS_CERT_PATH}
      - VPN_SENTINEL_TLS_KEY_PATH=${VPN_SENTINEL_TLS_KEY_PATH}
      - VPN_SENTINEL_SERVER_ALLOWED_IPS=${VPN_SENTINEL_SERVER_ALLOWED_IPS}
      - VPN_SENTINEL_SERVER_RATE_LIMIT_REQUESTS=${VPN_SENTINEL_SERVER_RATE_LIMIT_REQUESTS:-30}
    networks:
      - vpn-sentinel-internal
      - vpn-sentinel-server
    restart: unless-stopped

networks:
  vpn-sentinel-internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
  vpn-sentinel-server:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16
